gballet/go-ethereum

core/blockchain.go, eth/api.go
- `eth2_produceBlock`
- add a delay that waits for a second if block is about to be produced with the same `timestamp` as its parent, otherwise produced block fails on import
- `log.Info("Produce block", "parentHash", parentHash)`
- `eth2_insertBlock`
- replace  `InsertChain` with `InsertChainWithoutSealVerification` in `eth2_insertBlock`
- `eth2_setHead`
- replace `api.eth.BlockChain().GetBlockByHash(api.head)` with `api.eth.BlockChain().CurrentBlock()`
- take a quit if given head is the same as the current one
=> Fix and polish eth2 API

trie/stacktrie.go
These changes reduces the allocs and allocated bytes (heap allocs) quite substantially.
```
name                       old time/op    new time/op    delta
DeriveSha200/std_trie-6       565µs ± 8%     590µs ±16%     ~     (p=0.310 n=5+5)
DeriveSha200/stack_trie-6     534µs ±11%     452µs ± 4%  -15.42%  (p=0.008 n=5+5)
name                       old alloc/op   new alloc/op   delta
DeriveSha200/std_trie-6       274kB ± 0%     274kB ± 0%   +0.02%  (p=0.008 n=5+5)
DeriveSha200/stack_trie-6     111kB ± 0%      56kB ± 0%  -49.73%  (p=0.008 n=5+5)
name                       old allocs/op  new allocs/op  delta
DeriveSha200/std_trie-6       2.86k ± 0%     2.86k ± 0%     ~     (all equal)
DeriveSha200/stack_trie-6     1.86k ± 0%     1.43k ± 0%  -22.95%  (p=0.008 n=5+5)
```
But I figured I'd rather …
=> stracktrie: use pooling, less allocs

cmd/geth/main.go, cmd/geth/usage.go, cmd/utils/flags.go, core/tx_pool.go, eth/backend.go, eth/handler.go, eth/handler_test.go, eth/helper_test.go, eth/protocol_test.go
- TxPool does not process transactions unless node gets synced with the network. This behaviour is not that convenient for Eth1-Eth2 Merger setup
- `txpool.processtxs` was added that is unset by default and reflects behaviour before this change
=> Add txpool.processtxs flag allowing for process txs upon node launch

trie/encoding.go, trie/encoding_test.go, trie/stacktrie.go, trie/stacktrie_test.go
This changes the semantics if `hash()`, or rather, makes the semantics more clear. 
Previously, `hash()` modified the object sporadically, and there was another method `convertToHash` which converted it into a hashedNode. 
The new semantics are that `st.hash()` does exactly what `convertToHash` did. After `hash` is called, the type is `hashedNode`, and the `val` is either the hash or, if `<32bytes`, the rlp-encoded value. 
This PR also shaves off some allocations, by
- converting from expanded keys to compact keys in-place. 
- resetting byte-arrays with `[:0]` rather than nilling them
- reusing the `val` arrays, if they exist, instead of always allocating a new buffer
=> Pass test derivable list

core/types/derive_sha.go, trie/database.go, trie/encoding.go, trie/encoding_test.go, trie/stacktrie.go, trie/stacktrie_test.go
These are the changes needed for `TestDerivableList` to pass:
* include the required change for `rawNode` to be serialized correctly
* alternative to `force`: make sure that the root of a trie is hashed if its length is less than 32 bytes
* remove one of @holiman's alloc optimization because it doesn't seem to work properly, have to investigate why
=> trie: pass TestDerivableList

cmd/geth/snapshot.go
Curious why the order matters in this case :think:
=> verkle: fix flush when computing commitment

core/chain_makers.go, core/state/snapshot/snapshot.go, core/state_processor_test.go, core/state_transition.go, core/types/access_witness.go, core/vm/gas_table.go, core/vm/interpreter.go, params/protocol_params.go, trie/verkle.go
=> test stateless block execution

consensus/clique/snapshot_test.go, core/chain_makers.go, core/genesis.go, core/state/statedb.go, core/state_transition.go, core/types/access_witness.go, core/vm/gas_table.go, core/vm/interpreter.go, core/vm/jump_table.go, eth/gasprice/gasprice_test.go, tests/block_test_util.go, trie/verkle.go
=> fix leaf proofs in stateless execution

cmd/geth/chaincmd.go, cmd/geth/main.go, cmd/geth/usage.go, cmd/utils/flags.go, consensus/misc/eip1559_test.go, core/blockchain.go, core/genesis.go, core/state_processor_test.go, core/vm/interpreter.go, eth/tracers/tracer_test.go, params/config.go
Enable verkle using `cancunBlock` in genesis config.  Must be block 0 (for now).
example genesis:
```
{
"config": {
"chainId": 86,
"homesteadBlock": 0,
"daoForkBlock": 0,
"daoForkSupport": true,
"eip150Block": 0,
"eip150Hash": "0x2086799aeebeae135c246c65021c82b4e15a2c451340993aacfd2751886514f0",
"eip155Block": 0,
"eip158Block": 0,
"byzantiumBlock": 0,
"constantinopleBlock": 0,
"petersburgBlock": 0,
"istanbulBlock": 0,
"muirGlacierBlock": 0,
"berlinBlock": 0,
"londonBlock": 0,
"cancunBlock": 0,
"ethash": {}
},
"nonce": "0x56",
"timestamp": "0x0",
"extraData": "0x",
"gasLimit": "0x2fefd8",
"difficulty": "0x1",
"mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
"coinbase": "0x0000000000000000000000000000000000000000",
"alloc": { …
```
=> enable verkle on cancun block: take 2

trie/utils/verkle.go
* Fix slot number calculation, which had a sign error
* Do not use a `uint256.Int` to compute a simple modulus
=> fix calculation in get_tree_key_for_storage_slot

miner/worker.go, miner/worker_test.go
Get the RLP of a block: `curl -H 'Content-type: application/json' -X POST --data '{"jsonrpc":"2.0","method":"debug_getBlockRlp","params":[1],"id":83}' localhost:8545`
Example program to decode a returned block's RLP:
```
const verkleBlockRlp = "..."
let {rlp} = require('ethereumjs-util')
const b = Buffer.from(verkleBlockRlp, 'hex')
console.log(rlp.decode(b))
```
Output before this change:
```
[ [ <Buffer 72 93 56 f6 1c 03 c0 97 5c 73 bf e7 55 c3 e0 80 70 83 55 77 c7 9f fe c0 fe 17 4c 81 ba 25 35 b5>,
<Buffer 1d cc 4d e8 de c7 5d 7a ab 85 b5 67 b6 cc d4 1a d3 12 45 1b 94 8a 74 13 f0 a1 42 fd 40 d4 93 47>,
<Buffer a8 ea 39 1e ac d8 6a b3 26 84 35 79 06 0e 42 00 7a 5f a9 3b>,
<Buffer 0f 14 23 c8 31 98 43 77 25 87 92 29 2e 72 53 ff ce 9c c5 98 50 82 67 95 b2 b8 00 95 e1 db db 23>,
<Buffer 56 …
```
=> miner: embed verkle proof in sealing block

consensus/ethash/consensus.go, core/state_processor.go, core/state_transition.go, core/vm/common.go, core/vm/evm.go, core/vm/gas_table.go, core/vm/instructions.go, core/vm/interpreter.go, core/vm/jump_table.go
Moves witness accumulation logic that involves touching a range of EVM code that can span multiple tree leaves into its own method.
There's some other unrelated changes packaged in with this one:
* charge witness gas costs for `PUSH`
* ~~move all witness gas charging out of `gas_table.go` and into `instructions.go`~~
* adds missing checks elsewhere to only build witnesses when verkle is enabled.
=> Refactor witness-accumulation in EVM

consensus/ethash/consensus.go, core/evm.go, core/state/statedb.go, core/state_processor.go, core/vm/evm.go, core/vm/instructions.go, miner/worker_test.go
Ensure that the tests pass if I deactivate witnesses in general tests. This includes part of the recommended fix for #47.
:warning: :skull_and_crossbones:  this doesn't change the fact that calculating an address is very slow with the proposed "pedersen hash" scheme.
=> fix for unit tests: do not call NewAccessWitness in NewEVMTxContext

consensus/ethash/consensus.go, core/evm.go, core/state/statedb.go, core/state_processor.go, core/vm/evm.go, go.mod, go.sum, miner/worker_test.go, trie/utils/verkle.go
Hashing has been entirely removed from the verkle tree EIP, in order to increase its friendliness to zks.arks. This PR implements the `perdersen_hash` function.
TODO: rebase on the main branch once #45 has been merged,
=> replace sha256 with pedersen_hash in get_key

core/vm/contract.go, core/vm/evm.go, core/vm/interpreter.go
Don't charge witness access costs for the executing bytecode or attempt include it in the proof.
Honestly, I think the functionality of querying to see if the current executing call frame is a constructor or on-chain code shouldn't go in the `AcessWitness`, but rather the `EVM`.  But I put it in the `AccessWitness` to avoid coupling a feature only needed by the `AccessWitness` with the `EVM` code.
=> Properly handle contract constructor bytecode with respect to AccessWitness

core/vm/analysis.go, core/vm/contract.go, core/vm/gas_table.go, core/vm/instructions.go, core/vm/interpreter.go
EXTCODECOPY isn't currently implemented because we don't have the ability to query whether a given bytecode offset is an opcode or push data if the contract we are querying is not the currently-executing one.  And we need this information to encode the "push-data offset" in the first byte of a leaf when building up the `AccessWitness` for the copied code.
The simplest way to implement this is to do jumpdest analysis on the target contract every invocation of `EXTCODECOPY` which gives us a `bitvec` object to query what we need.  That is what this PR implements and it should do the trick for now.
=> Verkle EXTCODECOPY implementation

core/chain_makers.go, eth/backend.go, go.mod, go.sum, trie/verkle.go, trie/verkle_iterator.go
=> verkle proof deserialization

miner/worker_test.go, trie/utils/verkle.go
The `subIndex` should be the last byte in the returned result.
=> Fix GetTreeKey

consensus/ethash/consensus.go, core/state_processor_test.go, core/state_transition.go, core/types/access_witness.go, core/vm/evm.go, core/vm/gas_table.go, core/vm/instructions.go, core/vm/interpreter.go, params/protocol_params.go
Supersedes https://github.com/gballet/go-ethereum/pull/37
=> Implement latest stateless gas charging spec

core/state_processor_test.go, core/types/access_witness.go
And multiple calls to `SetLeaf` also overwrote the initial data in the access witness.
=> fix: witness gas costs being charged more than once

core/chain_makers.go, miner/worker.go
Out of the 3 proposed solution, this implements the least efficient one: Keep a copy of the pre state lying around. This is good enough for the prototype.
=> copy the pre-state, use an untouched copy for the proof

core/state_processor_test.go, trie/verkle_test.go
serialized proof:
`00000000030000000a0a0a06000000c957349a475288eba5b2a85574fe74d241e8344dd5cf6a22c329e126f78ac9d8d1c8eb8d67632e12df72129e4d4cc112da1547552b5f09c1ef68f065a2845bba93d0cd08550afe90f862d3e5c87cecb4ad2cc6a1702f6e9a42e3a2530a07cb5bb195f6fbe8bc1af65b68b5cbba45dca5a42eb3d8ccbf991d0dea7460d0cd36c801e91e8dbe0d5694ce01aef119c639d4297aa31f6b9080671682f2f111ce420e5f6cd17839f8598d0f9d48873c59ff44fca2e8acb9830570a35bf47b078d62a40e76e246c3789dacb5085f74b1051e4ad6a3ad7f8d245d9a026320e3a13a2a726336ef2712b129aee9268235591dce4e7abfbcc2ba595d56a462a70aa3a13b5976120dfc081543f4e4c4783e95abb3553b70082814bb67b5bc765b1f82950b1b6b51562ac2293406b84e19a8cafd12e1cdd29149d656031c79a58e4663a0cc1af435d86d094d93c8faa6a8faba3a39fdedb095aeb2e88b4421d5431fa3fc24afbf3bc39657678bcb5009e4f642ae05e80b7b17234559577 …
=> test to compare the proof format with that of rust verkle

core/state/statedb.go
Leaving this one on draft for now as I need to think about what this could potentially break.  The only situation I can think of where we can get an empty `stateObject` is possibly upon the failure of a `CREATE`, but in this case it _should_ only exist as a `stateObject` and not in the trie yet.
=> core/state: don't delete an account from the trie if it becomes empty when verkle mode is enabled

core/state/statedb.go
Unsure why this was removed with the verkle changes.  Does the contiguous code exist in another key?
=> Write code to DB bucket keyed by code hash

core/chain_makers.go, go.mod, go.sum, miner/worker.go, trie/verkle.go, trie/verkle_test.go
These changes go along with https://github.com/gballet/go-verkle/pull/189 : the state root is a serialized point, not a serialized-point-turned-field-element.
=> fixes for the return type change in go-verkle

core/chain_makers.go, core/state/state_object.go, core/state/statedb.go, core/state_processor_test.go, core/state_transition.go, core/types/access_witness.go, core/vm/evm.go, core/vm/instructions.go, go.mod, go.sum, trie/utils/verkle.go
The values provided in the witness were wrong, as some were already overwritten compared to what they were in the pre-state.
To ensure that the initial value is loaded, catch them at the time they are first loaded from disk, by setting them in `getStateObject` instead of the evm.
TODO:
=> refactor: set witness account values in getStateObject()

trie/verkle.go, trie/verkle_test.go
In eth1, the code is implicitly suffixed with infinitely-many 0 bytes. This means that, for example, if:
* the last instruction in the code is a `PUSHn`,
* the push's immediate overflows the length of the suffix-less code,
* the push immediate also overflows the 31-byte chunk that the push instruction is in,
the question then arises whether or not to add one or more 0-filled chunks to the witness.
Before this PR, the code assumed that these extra chunks should be added. The spec, however, clearly states that they should not. This makes sense, because extra chunks translate into a bigger witness - and ultimately extra gas costs - when the client can easily determine that the code is truncated based on the codesize provided in the account header.
=> spec: don't add the trailing pushdata for a final PUSHn

core/vm/instructions.go, trie/verkle.go, trie/verkle_test.go
The fix already exists in `makePush`, however `PUSH1` doesn't make use of `makePush`.
=> fix: don't add PUSH1-data during contract deployment

go.mod, go.sum, trie/verkle_test.go
works in conjunction with gballet/go-verkle/pull/201
=> fix: redundant proof-of-absence stems

core/state/database.go, go.mod, go.sum, trie/verkle_iterator.go
Depends on gballet/go-verkle#202
When loading a tree from the db, the commitments were not assigned to the nodes.
=> fix: add commitments to nodes loaded from the DB

trie/utils/verkle.go, trie/verkle_test.go
Contrary to the verkle specs, 20-byte addresses were left-aligned.
Co-authored-by: Tanishq Jasoria <jasoriatanishq@gmail.com>
=> fix: ensure 20-byte addresses are right-aligned in pedersen_hash

core/vm/contract.go, core/vm/gas_table.go, core/vm/instructions.go, core/vm/interpreter.go
Adding the `AnalyzedContract` interface made it harder to rebase the PR. There is an alternative approach, which is to catch the analyzed data at contract creation time. This is what #57 will do, when updated and merged. In the mean time, `PUSH1` will be somewhat slower but it's acceptable at this stage.
=> Remove the code analysis interface to reduce PR footprint

core/state_processor_test.go
The call to `store` wasn't executing properly. Make sure that all pages that contain execution are present in the witness.
=> verkle test: count the code chunks in the witness

trie/utils/verkle.go, trie/verkle_test.go
The endianness of `pedersen_hash` has changed when switching to Banderwagon. This is a problem because Pedersen hashes are field elements of width 253 bits. Using the top 31 bytes in big endian mode means that only 115 subtrees are used out of 256, thus making the tree unbalanced.
Until Banderwagon is switched to little endian, this change will swap the endianness of the pedersen hash output to take the 31 least significant bytes when calculating a tree address.
=> temp fix: little endian pedersen_hash

core/types/access_witness.go
`GetTreeKey` is very slow, so not calling it too many times should greatly increase performance.
=> factor the amount of polynomial evaluations in access witness

core/genesis.go, core/state/state_object.go, core/state/statedb.go, core/types/gen_account_rlp.go, core/types/gen_header_rlp.go, core/types/gen_log_rlp.go, core/vm/instructions.go, core/vm/interpreter.go, go.mod, go.sum, miner/worker.go, miner/worker_test.go, trie/verkle.go, trie/verkle_test.go
Flatten all code chunks into a single buffer.
This represents yet another approach to integrate code chunking in geth: instead of hacking the interface to pass the chunks along with the code, just return the chunked code in its place. This will have an impact on the tracking of the program counter by the interpreter loop, but it should be less invasive than a full interface change.
=> core, trie: flatten all chunks into a single linear buffer

core/state/statedb.go, core/vm/instructions.go, core/vm/interpreter.go, go.mod, go.sum, trie/verkle.go, trie/verkle_test.go
#128 causes the testnet to fail, so I am slowly replaying all optimizations found in the replay branch, in order to figure out where the problem is.
This PR simplifies the signature of `ChunkifyCode` and uses `InsertStem` in order to update the account all at once. It also upgrades go-verkle to the latest commit before `ParseNode` returned `StatlessNodes` instead of `InternalNode`
=> first batch of optimizations from the replay code

core/types/access_witness.go, core/vm/contract.go, core/vm/gas_table.go, core/vm/instructions.go, core/vm/interpreter.go
It also caches which chunks have already been charged, so that they are not charged more often than necessary.
=> add a Chunks member to Contract so ChunkifyCode isn't called as often

trie/utils/verkle.go
This fixes an inefficiency: `Bytes` is called on a `uint256`, which is unnecessary because `uint256` is already a series of `uint64` and the relevant byte can be accessed directly.
To be tested on ARM before merging. This should save on allocations, although it is unlikely to increase performance much.
More work need to be done in this area in order to get rid of the uint256.
=> don't call Bytes() in GetTreeKey

cmd/geth/verkle.go, go.mod, go.sum, trie/utils/verkle.go, trie/utils/verkle_test.go, trie/verkle.go, trie/verkle_iterator.go, trie/verkle_test.go
This PR avoids unnecessary endianness conversion in `GetTreeKey(...)` because of two facts:
- [A tentative PR in `go-verkle`](https://github.com/gballet/go-verkle/pull/300) to allow using an API from `go-ipa` to transform a big-endian array to a `Fr`.
- A clever-ish idea to avoid an intermediate endianness conversion at this layer.
Running the `BenchmarkPedersenHash` against the previous implementation:
```
name             old time/op    new time/op    delta
PedersenHash-16    9.74µs ± 3%    9.62µs ± 1%   -1.17%  (p=0.010 n=30+24)
name             old alloc/op   new alloc/op   delta
PedersenHash-16      160B ± 0%      128B ± 0%  -20.00%  (p=0.000 n=30+30)
name             old allocs/op  new allocs/op  delta
PedersenHash-16      3.00 ± 0%      2.00 ± 0%  -33.33%  (p=0.000 n=30+30)
``` …
=> trie: avoid endianness conversion in GetTreeKey

consensus/ethash/consensus.go, core/chain_makers.go, core/state/state_object.go, core/state_processor_test.go, core/types/access_witness.go, core/vm/evm.go, core/vm/instructions.go
The complexity associated with getting `AccessWitness` to keep track of initial values is the cause of many maintenance headaches, as well as being ultimately broken since the proof creation ends up calling `Get` on the pre-state tree anyway.
In order to reduce the final complexity, this PR is a cleanup that removes all `SetLeafValues` and generates the proof at the end of the block execution, so that it can easily be deactivated.
TODO
=> core: do not make AccessWitness capture initial values

consensus/ethash/consensus.go, core/chain_makers.go, core/genesis_test.go, core/state/state_object.go, core/state_processor_test.go, core/state_transition.go, core/types/access_witness.go, core/vm/evm.go, core/vm/instructions.go, go.mod, go.sum, trie/verkle.go
The test still won't pass because `ParseNode` is currently returning `StatelessNode` and these nodes don't return `Fis`.
=> upgrade go-verkle to pre-CoW version and get TestProcessVerkle to build

core/state/state_object.go, trie/utils/verkle.go, trie/verkle.go
These that are fixes for issues that have been identified on beverly hills after the relaunch, although they certainly affect Condrieu as well:
* `TryUpdate` for `VerkleTrie` didn't make a copy of a buffer that was being reused, so the same, last value would be copied over all the inserted values;
* The computation of the offset for slots outside of the header group were incorrect (off by 64)
=> fix: storage offset in non-header group + reuse of value buffer

core/state/statedb.go, core/types/access_witness.go, core/vm/instructions.go, miner/worker_test.go
This change was already present in the block replay branch, but had not been transferred to the Beverly Hills branch.
=> dedup call to ChunkifyCode, same as replay branch

core/state/statedb.go
This fixes an offset issue in the computation of the offset for each code chunk. The "128 bytes in the offset" header was forgotten.
There is an opportunity for optimization here, since the code size is computed at the same time, but that will be done in a subsequent PR as I want to ensure correctness before I seek performance.
=> fix code offset in tree update

core/state/statedb.go, trie/verkle.go
In order to reduce the amount of hashing that is performed, reuse the key value of the first code chunk group in order to also store the code size.
=> save on key hashing: lump code size update with first code chunk group

core/blockchain.go, go.mod, go.sum
This PR:
- Updates to `go-verkle@master`
- Fix the converted hash.
cc @gballet to review.
=> update go-verkle and conversion hash

core/vm/instructions.go
See #151, this is simply applied to a different branch.
=> fix: infinite loop when calling extcodecopy on empty code

core/state/statedb.go
This reduces the (old) replay branch execution time by 20s
=> fix: only update dirty code

core/blockchain.go, go.mod, go.sum, trie/verkle.go
This PR uses a new go-verkle batch serialization API enabled in https://github.com/gballet/go-verkle/pull/333
Review notes:
- I'd suggest to review https://github.com/gballet/go-verkle/pull/333 first, and then jump back here.
=> Use new go-verkle batch serialization

go.mod, go.sum, trie/verkle.go
This PR:
- Updates `go-verkle` to the latest commit of a new rebased version of [Batch Serialization PR](https://github.com/gballet/go-verkle/pull/333/commits). Now is sitting on top of `go-verkle@master`, and should be our fastest version.
- Pulled the corresponding updated code for `trie/verkle.go` `Commit()` code that leverages that new API.
- Double checked and we already have latest go-ipa from ~yesterday.
=> use fastest non-master go-verkle version & pull trie/Verkle.go changes to use new api

core/chain_makers.go, core/state/database.go, core/state/state_object.go, core/state/trie_prefetcher.go, go.mod, go.sum, light/trie.go, trie/secure_trie.go, trie/trie.go, trie/utils/verkle.go, trie/verkle.go
Instead of creating an adapter, which would need to recover the address anyway, this PR modifies the `Trie` interface in order to pass the address.
=> alter Trie interface to use caching for slots

.github/workflows/go.yml
Download the latest precomp file. If we don't do this, we'll get some errors in our CI.
See https://github.com/gballet/go-ethereum/issues/186
=> ci: update precomp download link

trie/utils/verkle.go
This goes back to our known `4ff31341ec17af3df4ecebbde12c2e632fba6641a56c95d624c4e3ab8a945276`.
=> trie/utils: fix incorrect bigint assignment

cmd/geth/verkle.go
Until now, the code size and keccack for an EoA wasn't stored. This PR fixes that.
=> fix: add missing code size&keccak leaves in empty accounts

core/blockchain.go, core/chain_makers.go, core/genesis.go, core/state/access_witness.go, core/state/database.go, core/state/statedb.go, core/state/statedb_test.go, light/trie.go, trie/database.go
This is a preparation for the rebase on top of master: instead of using a custom `VerkleDB`, implement the equivalent of `ForkDB` from the overlay method, and call the `EndVerkleTransition()` method in order to switch to verkle mode. In particular, calling it at genesis time will make for a fully verkle network.
=> use the cachingDB instead of a custom VerkleDB

core/state/database.go, core/state/iterator.go, core/state/state_object.go, core/state/trie_prefetcher.go, les/server_requests.go, light/odr_test.go, light/trie.go, trie/verkle.go
Implement `OpenStorageTrie` to return the main tree, so that there is less of a need to check for the trie type in `statedb.go` & `state_object.go`.
**NOTE** this will kill performance because the trie root will be calculated each time that a storage trie's `Commit` method will be called. A fix for this consists in adding an adapter pattern to hold that `Commit` should be a no-op. This PR shoots for correctness, not performance.
=> implement OpenStorageTrie for verkle trees

trie/verkle.go
This is an error that popped up while attempting to remove the snapshot in tests: the buffer containing the data corresponding to an account's balance is endian-swapped and before  being copied to a `big.Int`. This means the value in the trie is endian-swapped, and then saved as such when it's serialized. This will cause some commitment computation errors (on top of being the incorrect data).
=> fix: copy balance leaf to new buffer in TryGetAccount

trie/transition.go, trie/verkle.go
A bug was found, that was caused by an account created in MPT mode, being selfdestructed in verkle mode: getting the account from the overlay tree would report a missing account, which meant that the transition tree would go and get the data from the MPT, in which the account was not selfdestructed.
=> fix: use an error to notify the transition tree that a deleted account was found in the overlay tree

core/state/database.go, trie/verkle.go
This PR:
- Honors IdealBatchSize for DB batch inserts.
- Changes N allocations per numbers of nodes saved in the db per Commit, to only 1.
=> trie/verkle: use capped batch size

core/state/statedb.go
Separate the snapshot-reactivation from #226 in order to attribute a potential performance gain to it (as activating Cancun will likely kill performance).
=> re-enable snapshot

core/blockchain.go, core/state/access_witness.go, core/state/database.go, params/protocol_params.go
This PR forces the `CancunBlock` to be set when the verkle transition starts, and ensure that the translated root is used to find the snapshot.
=> re-enable cancun block

core/state/database.go
This fix a deadlock in which the insertion goroutine reserves a lock in read mode, the prefetcher goroutine contends for that same lock in read mode, and then the initial goroutine contends for that lock in write mode. I have tested the fix and it works.
=> fix: self-deadlock with translated root map mutex

trie/verkle.go
This is the last missing piece before pbss/replay-fixes can be merged into the pbss PR, so that everything can be collapsed into a PR that is ready for rebase.
=> return compressed commitment as root commitment

core/state_processor.go
This PR adds a log line to print the current state tree root hash every 100 blocks.
Example screenshot:
(I haven't seen how verbose this frequency is for after-migration, but for the throughput we've seen lately, I think it should be fine. Also, at some point in the future this log line will be removed)
=> print state root every 100 blocks

core/chain_makers.go, core/state/database.go, core/state/statedb.go, core/state_processor_test.go, go.mod, go.sum, trie/transition.go, trie/verkle.go
Fixes a series of errors that got introduced with the overlay method, and who broke the verkle state processor test.
The basic problem is that the new type of tree, `TransitionTrie` wasn't supported by these tests, as a `VerkleTrie` was directly created for networks starting with a verkle genesis, and the overlay code assumes that there is always a transition period. The final fix will be to set the transition period as having ended at the genesis, for networks with verkle at genesis.
The dependency on the db in `(*VerkleTrie).CopyTrie` has also been removed for simplification.
There has been further simplifications in the base branch, and `ForkingDB` can be removed now that `TransitionTrie` does all the conversion job. This is not the purpose of that PR, though.
=> fixes to get TestProcessVerkle to work with the overlay branch

core/state/database.go, trie/verkle.go, trie/verkle_iterator_test.go
During the transition, when a deleted account has been found, a special error is returned so that the `TransitionTrie` knows that a deleted account was found in the verkle tree, and that it should not try to search the MPT for an older version of that account.
Once the transition has ended, `TransitionTrie` is no longer used, and so that error should not be sent. This PR makes sure that is the case.
Such an instance occurs around block 4,713,525.
=> fix: vkt delete in transition in cachingdb rebased

cmd/geth/chaincmd.go, cmd/geth/main.go, cmd/utils/cmd.go, cmd/utils/flags.go, core/state/database.go, core/state_processor.go, light/trie.go
This is a PR that:
- Adds a tool for exporting preimages in a flat file in the same order they'll be walked in the Overlay Tree migration.
- Use this file in the overlay tree migration.
This PR is a draft, and only the first bullet is in... it will continue to evolve, including the second bullet.
To run the tool: `go run ./cmd/geth --datadir=/pathto/.ethereum export-overlay-preimages preimages.bin`
=> Overlay Tree preimages exporting and usage

core/state/state_object.go
This is a leftover from the time that a verkle tree could only be an account trie. I tested the fix on mainnet, want to see if the tests are passing.
=> fix: reduce the PR footprint

core/state_processor.go
#246 introduced the issue that all tests would fail if no `preimages.bin` was present.
There are two aspects to this:
1. the check for preimages is made outside of the check whether a verkle transition is active
2. if the preimage file is missing but preimages are available, the preimage db should be used
=> fix: don't fail when preimages.bin is missing

consensus/beacon/consensus.go, consensus/ethash/consensus.go, core/state/access_witness.go, core/state/statedb.go, core/state_processor.go, core/vm/contract.go, core/vm/evm.go, core/vm/gas_table.go, core/vm/instructions.go, core/vm/interpreter.go, core/vm/operations_acl.go, trie/utils/verkle.go, trie/verkle_test.go
This PR is a new version of the access-witness module that avoids doing Pedersen Hashes and does the accounting using the preimages. A way to look at that is closer to how access-tracking is explained in the EIP.
It indirectly forced callers to eagerly get all contract codes and calculate the tree keys for each chunk, even if they aren't touched. So some other indirect simplifications; at some point I'll create PR comments to explain this better.
TODO:
=> New access-witness module

trie/utils/verkle.go
This PR eliminates the usage of `big.Int` when calculating the tree-hash for a storage slot.
It does some careful calculations using `u256.Int` to avoid any potential overflow.
=> verkle: remove allocations for storage slot tree calculation

core/state_processor.go, trie/utils/verkle.go
This PR creates a new optimized version of keyValueMigrator, which:
It avoids calculating Pedersen Hashes while walking the base tree, so we only deal with collection values.
We parallelize the work of the Pedersen Hashing after the current walk for the block finishes, which makes it faster.
We architect the pipeline to allow the heavy CPU work (which doesn't touch the tree) to be executed in parallel with the block execution. (This isn't done in this PR since we have a bug that doesn't allow us to do it, but things are left in a way that's easy to do as soon that's fixed).
This has improved performance by 15-20% of our overlay-tree benchmark.
This PR is left in draft mode until our merging pipeline gets cleared up a bit since this PR is sitting on top of another pending one. PR comments …
=> core/state: rewrite a new optimized keyValueMigrator

core/overlay_transition.go, core/state_processor.go
The post-shapella Kaustinen performs a transition right after genesis. To do so, the transition code needs to be called in two locations: 1) the block production code (block producer only) 2) the block insertion code (everyone).
This PR moves the transition code to its own function/file, so that it can be managed better. It should also help with merging the final PR into geth.
=> core: move overlay conversion code to its own file

consensus/beacon/consensus.go, core/state/database.go, core/state/statedb.go, core/state_processor.go, miner/worker.go
It introduces a dependecy cycle in tests, which is not great, but besides the point for now.
=> fixes from trying to get the devnet to work

trie/verkle.go
The following stack trace was reported for kaustinen:
```
goroutine 208183 [running]:
[github.com/ethereum/go-ethereum/trie/utils.(*PointCache).GetTreeKeyHeader(0x0,](http://github.com/ethereum/go-ethereum/trie/utils.(*PointCache).GetTreeKeyHeader(0x0,) {0xc000b377e8, 0x14, 0x14})
[github.com/ethereum/go-ethereum/trie/utils/verkle.go:65](http://github.com/ethereum/go-ethereum/trie/utils/verkle.go:65) +0x31
[github.com/ethereum/go-ethereum/trie/utils.(*PointCache).GetTreeKeyVersionCached(0x1a16820?,](http://github.com/ethereum/go-ethereum/trie/utils.(*PointCache).GetTreeKeyVersionCached(0x1a16820?,) {0xc000b377e8?, 0xe29a1b?, 0x4d?})
[github.com/ethereum/go-ethereum/trie/utils/verkle.go:80](http://github.com/ethereum/go-ethereum/trie/utils/verkle.go:80) +0x1e …
```
=> fix: ensure point cache isn't nil in copy

core/blockchain.go
It seems that the recording of preimages coming from the tree was broken before PBSS. This is a fix, I still need to check if it is still currently needed in geth master.
=> fix: write trie preimage data to db

core/blockchain.go, core/state/database.go, eth/catalyst/api.go, light/trie.go, trie/verkle.go
The miner always creates an empty block, to make sure that one block will always be ready to deliver if the block production window expires. If a better block is produced before the end of the window, that new block will replace the empty block.
But with the empty block, `EndVerkleTransition` has already been called (if it's the end of the transition). So the `ended` variable is set to `true` while another block at the same height is being created. Result: the parent state root parameter in `OpenTrie`, which can be a MPT root, is interpreted as the root of a verkle tree. Since this root can't be found as a verkle root, it starts an empty verkle tree.
Before the sync starts, the syncing node will create a first block on top of the genesis. Because by then, the `pragueTime` has passed, the …
=> fix: zero-root in produced block + sync

consensus/beacon/consensus.go
This needs to be merged before the rebase, as the access witness API has changed.
=> add fee recipient to witness

consensus/beacon/consensus.go
after a discussion with Tanishq, it became obvious that the entire account header needs to be touched for the withdrawals.
=> touch all fields in withdrawal account header

consensus/beacon/consensus.go, core/state_processor_test.go, params/config.go
The field `proofInBlocks` need to be set to `true` in the genesis configuration.
=> fix: add ProofInBlocks to chain config

core/genesis.go
This is a workaround for #264: the genesis code tries to load the root from the tree, using the standard database schema.
The schema that is currently used is different, so it will not find the root. Since this check is not necessary for a kaustinen startup, deactivate it.
=> workaround: disable check for root presence

cmd/geth/chaincmd.go
Verkle mode wasn't activated in the `triedb` which means that the genesis allocation data was stored in an MPT, in spite of the root hash being correct.
=> fix: activate verkle at genesis

consensus/beacon/consensus.go
The values that are read but not updated during block execution, will be read straight from the snapshot and will not be resolved inside the tree.
This would normally be done by the prefetcher, which is currently disabled in verkle mode. So this PR adds a workaround to read all values from the tree to ensure that they are resolved.
=> fix: ensure read-only values are resolved in post trie

consensus/beacon/consensus.go, core/state_processor_test.go, go.mod, go.sum, trie/verkle.go
This PR does some client-side changes to adjust proofs to not include post-state values.
It depends on https://github.com/gballet/go-verkle/pull/407 being merged.
=> proofs: remove post-values in Multiproof

.github/workflows/go.yml, cmd/geth/verkle.go, go.mod, go.sum, trie/transition.go, trie/verkle.go
This PR updates `go-verkle` which includes the following merged PRs:
- https://github.com/ethereum/go-verkle/pull/410 (extra proof checks)
- https://github.com/ethereum/go-verkle/pull/411 (API changes)
- https://github.com/ethereum/go-verkle/pull/412 (very important proof format fixes)
=> mod: update go-verkle

cmd/geth/chaincmd.go, consensus/beacon/consensus.go, core/blockchain.go, core/chain_makers.go, core/genesis.go, core/overlay/conversion.go, core/overlay_transition.go, core/state/database.go, core/state_processor.go, light/trie.go, miner/worker.go
The base branch is able to perform the transition in one block, but it fails if there are more than one block. The problem stems from the fact `ended` and `started` are global variables, and that during block creation, several attempts are made at creating a block with a different tx set each time. So the state transition pointers were incorrect. To make things worse, once the block has been created, it's passed to the CL, and the latter passes it back to the EL for insertion, at which points the block is re-executed.
This PR implements a cleaner approach in which there is only one "active" set of conversion pointers at a time, but once the block has been created, these sets of pointers (called `TransitionState`) are saved on a per-root basis. This way, if (for whatever reason) multiple …
=> Refactor transition post genesis

core/state/database.go, core/state/trie_prefetcher.go
It seems that the prefetcher activates itself while not supposed to. This was a problem because the account trie was set to `nil` by default in this case.
In order not to crash, we just return an error if the tree is of the wrong type, and also we pass the actual account trie just in case.
=> fix OpenStorageTrie: return an error instead of panicking if the account tree not a verkle tree

cmd/geth/config.go, cmd/geth/main.go, cmd/utils/flags.go, core/blockchain.go, core/genesis.go, eth/backend.go, eth/ethconfig/config.go
This is for the case of a shadow fork, when the genesis can no longer be used. It introduces a `--override.proof-in-block` flag that will act as if the config option was present in genesis.
=> add a switch to force proof in blocks

cmd/geth/config.go, cmd/geth/main.go, cmd/utils/flags.go, consensus/beacon/consensus.go, core/blockchain.go, core/genesis.go, core/overlay/conversion.go, eth/ethconfig/config.go, params/config.go
For easier testing, make the stride of the overlay snapshot iterator an external parameter. This is so that we can try the transition over many blocks with a smaller set of leaves in the tree.
The issue of this PR is that now, the switch needs to be set manually or `OverlayStride` needs to be set in the genesis file. Otherwise, we effectively have the "state expiry method"
=> add switch to override the stride of the overlay conversion

trie/utils/verkle.go
`MAIN_STORAGE_OFFSET` is specified at $256^{31}$ and it is currently coded at $256 \times 2^{31}$. This PR fixes it to match the spec.
=> fix: main storage offset value

core/state/access_witness.go, core/state_processor_test.go
This PR modifies how we charge `from` and `to` in the access witness.
The goal is to have a minimal change that would keep the currently expected 21000 gas for simple transfers, such that we avoid breaking potentially many hardcoded rules in existing toolings.
=> accesswitness: avoid charging cost for origin and target

consensus/beacon/consensus.go
`FinalizeAndAssemble` was not loading the conversion pointers unless `--override.blockproof` was set. This caused some issues on the shadowfork as the pointer would not be reinitialized when the client tries to produce the same block multiple times.
=> fix: load conversion state in FinalizeAndAssemble

core/vm/interpreter.go, core/vm/jump_table.go
Selfdestruct was reactivated when I did the rebase, since it is now activated in `cancunInstructionSet`. Create a `pragueInstructionSet` that does exactly the same thing.
=> force activation of EIP-6780

consensus/beacon/consensus.go, core/state_transition.go
This PR moves the "touching" of the coinbase from `Finalize` to the state transition proper, so that the value is only added to the witness in case that coinbase is non-zero. This is only an issue in testnets, but it makes sense to activate that as it is confusing to testnet developers.
=> only add the coinbase to the witness if the block reward > 0

core/state_processor_test.go, trie/utils/verkle.go
~~The suffix value for a slot was not computed properly: 64 weren't subtracted in order to account for the first 64 slots being in the account header.~~
This PR also adds tests that verify the content of the produced witness, and ensure that the main storage slots will end up where they should. These tests add several transactions taken from Kaustinen (really `verkle-gen-devnet-2`), which are contract creation transactions that fail during the execution of the init code. The first two of these transactions are in the first block, and perform a `SSTORE` before the init code reverts.  This means that these values should end up in the witness. The third, in the second block, immediately reverts and so the witness should show no proof of absence at code locations.
=> test: check witness when contract creation fails

cmd/evm/internal/t8ntool/execution.go, cmd/evm/internal/t8ntool/gen_stenv.go, core/state_processor.go, core/vm/instructions.go, miner/worker.go, params/protocol_params.go
Same as the one against geth's `master`, but adds the leaves to the witness. This means that the first BLOCKHASH call will create two extra entries in the witness: we use the contract to check if the transition has happened.
=> implement eip 2935

cmd/geth/config.go, cmd/geth/main.go, cmd/utils/flags.go, consensus/beacon/consensus.go, core/blockchain.go, core/overlay/conversion.go, core/state/database.go, core/state/statedb.go, core/vm/instructions.go, miner/worker.go, trie/transition.go
This is meant for shadow forks, in order to ignore the witness costs so that transactions are not failing as much.
This branch has received a lot of updates that have nothing to do with the initial command, and needs cleanup.
=> cmd/{geth, utils}: add a command to clear verkle costs

consensus/beacon/consensus.go
The current conversion code panics if it tries to create a proof at the first block. This is because the previous tree is a MPT and no verkle proof can be made against the MPT.
As a result, this PR swaps the MPT with an empty verkle tree, so the proof will be against an empty verkle tree, which is the correct interpretation of a transition proof.
=> fix: support a verkle pre-tree at the conversion block

cmd/geth/chaincmd.go
Verkle mode is hardcoded in the `init` command, this should not be the case: it should be taken from the genesis data.
=> fix: decide if genesis is verkle using genesis timestamp

cmd/geth/chaincmd.go, core/genesis.go, core/state_processor.go
This is porting the verkle activation from geth master. Now, `geth init` should work in verkle mode by just specifying `--override.prage=<genesis timestamp>`.
=> set verkle mode from genesis with override

core/genesis.go
#283 introduced a workaround in order not to call `HasLegacyNode`, which had no meaning in the verkle world and was causing a root comparison to fail.
Because the branch was meant to be temporary, this workaround made sense. But now that it has become somewhat official, it makes sense to make this workaround a bit more stable, since it creates a deadlock in tests.
This PR only activates the workaround in the case of a verkle-at-genesis testnet.
=> fix: only disable HasLegacyNode call for verkle-at-genesis testnets

core/chain_makers.go
The eip2935 storage of a block's parent hash had not been activated in `chain_makers.go`, which broke the tests as the generated chain would not have the same state root as the inserted chain.
=> fix: eip2935 block hash storage in chain makers

core/genesis.go
Ensure that genesis pointer or any sub-field aren't `nil` when deactivating code that breaks the verkle genesis.
=> fix: nil pointer when deactivating verkle-incompatible genesis code

core/chain_makers.go
The `triedb` was recreated at each block, which is incorrect and inefficient. Move it out of the loop in `chain_makers.go`
=> refactor: move trieDB creation outside of block production loop

core/state_processor.go, core/state_processor_test.go
Adding this stem is necessary for the stateless execution to be able to determine if the block height is at least 256 blocks past the fork block, and therefore if it needs to activate.
=> Add eip2935 256th ancestor stem to witness

core/state/statedb.go, core/state_processor_test.go
This PR fixes a bug regarding the post-value of the history block hash contract being `unchanged`.
The reason is that EIP-158 was (correctly) deleting the account for this address since the code, balance, and nonce are zero.
I've confirmed this reproduced in the current test and added extra checks to enforce that it can't happen again (since the tests assertions where checking that the key was in the witness, but not the post-state value expectation).
=> state: make EIP-158 ignore history block hash contract address

core/blockchain.go
Tests don't initialize overrides, and that causes a panic when they run.
=> fix: check for nil override in NewBlockChain

cmd/evm/internal/t8ntool/execution.go, core/chain_makers.go, core/state_processor.go, core/vm/instructions.go, miner/worker.go
This is a rewrite of eip 2935 after it was suggested to simply insert all block hash values at fork time, instead of reading the 256th ancestor and using a complex fallback mechanism.
=> eip2935 redesign: insert all 256 ancestors upon transition

cmd/evm/internal/t8ntool/execution.go, cmd/evm/internal/t8ntool/flags.go, cmd/evm/internal/t8ntool/transition.go, core/state/database.go
Includes the following fixes:
- Really fix logging this time
- Add `--input.allocMPT` to the `evm` command, which can be used to supply the MPT during verkle transition
- Nil checks in `core/state/database.go` because we were getting some nil pointer exceptions when filling before verkle
Filling currently fails when the verkle transition is supposed to start due to `snapshot.New` returning a nil snapshot, possibly related to this? https://github.com/gballet/go-ethereum/blob/c3fc3b83ca1eeee246bf98e26bbcf441daeeba9f/core/state/snapshot/snapshot.go#L218-L228
Attached a zip to reproduce the issue, which is the current input we are producing using a Prague tests in execution-spec-tests.
[t8n_verkle_repro.zip](https://github.com/gballet/go-ethereum/files/14272477/t8n_verkle_repro.zip)
=> cmd/evm: fixes

core/state_processor_test.go, core/vm/instructions.go
This PR adds access witness recording for EXTCODEHASH
=> Record witness access in EXTCODEHASH

core/vm/instructions.go
This PR fixes a bug in the `endPC` calculation when touching code that caused an infinite loop (and thus OOM situation).
=> instruction: fix integer underflow that causes an infinite loop

core/state_processor_test.go, core/vm/instructions.go
This PR adds missing logic to record a witness access during BALANCE opcode execution.
=> Record witness access in BALANCE opcode

cmd/evm/internal/t8ntool/execution.go, cmd/evm/main.go
I noticed that the transition into the verkle fork was not being correctly detected by the `evm` tool using this logic:
https://github.com/gballet/go-ethereum/blob/19aac228111d0d539a103d88306836c83b5a81f3/cmd/evm/internal/t8ntool/execution.go#L374
And the reason is that, regardless of what type of test we are running, we never use a transition fork (such as `ShanghaiToPragueAtTime32`) as value for parameter `--state.fork`. We instead always pass the currently active fork (we go from `Shanghai` to `Prague` on the very next block), so `chainConfig.IsPrague(big.NewInt(int64(pre.Env.Number)-1), pre.Env.ParentTimestamp)` always returns `true`.
This PR proposes a new logic to follow to determine whether the conversion is ongoing or completed:
1) The tests will always pass …
=> cmd/evm: Changes to the verkle activation/conversion logic

core/state/access_witness.go
This PR fixes a problem in EXTCODESIZE when the slot value had a value <20 bytes.
=> fix addr alignment in witness

core/state/statedb.go, core/state_processor_test.go, core/vm/instructions.go, core/vm/interface.go, trie/verkle.go
This PR fixes SELFDESTRUCT behavior aligned with EIP-6780:
- It fixes a bug where we were doing "zero writes" to the tree in the case the contract calling SELFDESTRUCT was created in the same tx.
- If fixes a bug where we weren't doing proper touching in the witness for the SELFDESTRUCT beneficiary.
It also adds three tests to cover different cases.
=> Fix SELFDESTRUCT incorrect account zeroing & missing beneficiary balance in witness

.github/workflows/conversion.yml, core/overlay/conversion.go, core/state/database.go, light/trie.go
This is a heavy-handed approach compared to #382, but I hope that it would cause less problems. If this is confirmed to work, it will then make sense to try a more fine-grained approach.
=> Lock the state transition during conversion

.github/workflows/conversion.yml, consensus/beacon/consensus.go, core/overlay/conversion.go, core/rawdb/accessors_overlay.go, core/rawdb/schema.go, core/state/database.go, core/state_processor.go, light/trie.go
Some issue appeared in the shadowfork branch, due to the fact that when, for whatever reason, a new database is created, it will check if verkle was activated at genesis as a heuristic to determine if the transition has already happened. If so, it will declare `ended` as `true`.
When a block is inserted through the execution engine api, such a database is created, and it seems that it determines the activation of verkle the wrong way. This is because it uses the current time in order to see if verkle is active at genesis. This works at genesis, but if the database is created AFTER the verkle activation, it will assume that the transition has already completed. This creates a weird situation in which the miner produces a block whose conversion has started (and potentially completed) but …
=> persist conversion state to db and use an LRU cache for active transition states

cmd/evm/internal/t8ntool/transition.go, cmd/evm/main.go
Adds a helper command to compute a verkle tree key, given an account address and an optional slot number. Use as follows:
```
evm t8n verkle <address> [<slot>]
```
where `address` and `slot` are hexadecimal numbers prefixed by `0x`.
Note that this uncovered issue #394
=> add a helper command to compute the verkle address

core/state/database.go, eth/api_debug.go
This PR adds an RPC endpoint that returns two booleans:
- `Started` is `true` if the conversion has started
- `Ended` is `true` if the conversion has completed.
Nothing too surprising I believe.
=> eth: add debug_conversionStatus RPC call

core/vm/instructions.go
This PR was found by running our replay code in the latest changes.
The run had a panic [at this line](https://github.com/gballet/go-ethereum/blob/kaustinen-with-shapella/core/state/access_witness.go#L246), since `20-len(addr)` was negative which is an illegal index access. For context, we changed this line some days ago in https://github.com/gballet/go-ethereum/pull/366. 
That PR fix was fine since it fixes cases where `addr` length is less than 20. If we don't do `20-len(addr)`, the alignment is wrong. But the situation here is the inverse, if `addr` is longer than 20 bytes then we have this panic. From where this came from, it was the `BALANCE` opcode. 
The value of `BALANCE` is a 32-byte value that must be truncated for a correct interpretation of the address (since no address can be …
=> Truncate BALANCE opcode parameter for witness recording

core/vm/gas_table.go, core/vm/instructions.go
The replay found another case similar to https://github.com/gballet/go-ethereum/pull/397. I scanned for more similar cases and found one extra. 
Leaving some comments.
=> more address truncation fixes

core/state_processor.go, core/vm/instructions.go
This PR implements the proposed change of using a circular buffer to save BLOCKHASH data history.
Note: this change is planned for Kaustinen v5.
=> Use circular buffer for BLOCKHASH history

core/txpool/blobpool/metrics.go
This PR imports a commit from upstream to fix Prometheus metrics due to incorrect naming standards.
If we try to scrape the Prometheus metrics, an error will occur. Here's an example output of `http://<prometheus-server-ip>:9090/targets`:
After applying the fix, the Prometheus metric is working as expected. An example below shows the Grafana dashboard:
=> core/txpool/blobpool: fix metrics name for prometheus export (#27901)

go.mod, go.sum, trie/utils/verkle.go, trie/utils/verkle_test.go, trie/verkle_test.go
This PR changes how we transform a point to bytes to be used as a tree key.
~Note: still in draft since it's waiting for a small PR merge in go-verkle, but it's ready for review.~
Note: we should merge this PR as soon as the target branch is ready for the new testnet.
=> trie/verkle: change tree key generation

core/state_processor.go
This PR ensures that, when the history contract is created, and because its creation bypasses eip 158, we add the contact to the witness.
=> fix #365 in eip rewrite

core/vm/instructions.go
The BLOCKHASH instruction wasn't charging the witness cost.
=> core/vm: charge BLOCKHASH witness cost

.github/workflows/go.yml, core/state_processor_test.go
The `TestProcessVerkle*` tests weren't updated after the PR that changed the way we calculate tree keys.
=> Fix TestProcessVerkle* tests

core/state_processor.go, core/vm/instructions.go, params/protocol_params.go
This PR changes the block hash contract history to 8192 block hashes, but keeps the `BLOCKHASH` instruction have access to the last 256 ones.
=> core: change block hash history scope

core/vm/gas_table.go, core/vm/operations_verkle.go
This PR:
- Does some refactor to avoid duplicate work in CALL/CALLCODE/DELEGATECALL/STATICCALL witness events.
- Comply to the spec rule of only doing that if the target address isn't a precompile. Not only for the above instructions, but also for EXTCODEHASH, EXTCODESIZE and SELFDESTRUCT.
- Add a missing value-bearing charging for CALLCODE.
=> Fix precompile address checks & value bearing witness cost charging

core/vm/operations_verkle.go
This behavior is not explicitly specified in the spec. However, this change abides by the general design principle of EIP 4762, which is to make the gas changes behave like the pre-verkle ones, as much as possible.
When a contract selfdestructs and sends value to its designated beneficiary:
* the beneficiary is added to the access list
* if the beneficiary address is cold, charge the cold address access cost: 2600 gas
* otherwise, charge the warm address access cost: 100 gas
* if the selfdestruction sends value AND the beneficiary does not exist, charge `CreateBySelfdestructGas`, i.e. 25000 gas
In this case, it is quite difficult to charge the same gas, and the final charge will be slightly cheaper.
* touch the version, code size and balance of the self-destructing contract in READ access …
=> charge for account creation if selfdestruct creates a new account

cmd/evm/internal/t8ntool/transition.go, cmd/evm/main.go
Reintroduce the command to compute a single tree key. The single key command is called `verkle-key` and the one to compute an entire tree is called `verkle-keys`.
=> add back single key computation command

trie/utils/verkle_test.go
I have seen instances of `GetTreeKey` and `EvaluateAddress` + `GetTreeKeyWithEvaluatedAddress` have given different results. I was not able to reproduce it in the lab, so I assume that came from a poor use of the API. Nonetheless, it makes sense to add a test to run each time, so that we have an example to reproduce the problem in case it breaks.
=> add key comparison test

core/vm/instructions.go
This PR fixes a bug where the contract init witness logic is in the wrong place, making a `contract.UseGas(...)` quietly fail. 
The return value of `contract.UseGas(...)` isn't checked since it must never fail, but the witness cost addition in the wrong place makes this fail, so transactions can use more gas than they should.
=> core/vm: charge contract init before execution logic

trie/utils/verkle.go, trie/utils/verkle_test.go
This PR makes a slight change in `GetTreeKeyWithEvaluatedAddress` which allows to avoid copying the tree index to a separate array to accommodate for endianness. 
This is a trick I introduced a long ago in `GetTreeKey(...)` but was just missing in this other variant.
=> trie/utils: simplify GetTreeKeyWithEvaluatedAddress

core/vm/evm.go
During the geth review of the eip 4762 PR, we identified that `IsDeployment` was set at a location that was not necessary. This PR cleans it up in `kaustinen-with-shapella` as well, ahead of a rebase.
=> remove unused deployment detection code

.github/workflows/conversion.yml
This was supposed to be part of #426 but was broken when the traces that this was relying on were removed.
Luckily, a new debug RPC call was added to help kurtosis testing the holesky conversion. This test now uses this RPC call.
=> add quick conversion test

trie/verkle.go, trie/verkle_iterator.go
While working on a verkle-enabled `evm t8n`, I found out that the iterator was broken. This PR merges the fixes back into `kaustinen-with-shapella` so that I can keep the t8n PR minimal.
=> Fix iterator from t8n

cmd/evm/internal/t8ntool/transition.go, cmd/evm/main.go
This PR groups all existing commands in a new `evm verkle` parent command which:
- Rename previous `evm transition tree-key` to `evm verkle single-key`.
- Rename previous `evm transition tree-keys` to `evm verkle tree-keys`
- Add a new `evm verkle chunk-code-key` which calculates the tree key for a given code chunk number for an address.
- Add a new `evm verkle chunkify-code` which chunkifies a given bytecode.
Examples of running the new commands:
```
$ go run ./cmd/evm verkle code-chunk-key 0x95222290dd7278aa3ddd389cc1e1d165cc4bafe5 0x99
0x7a4c83df5aaf589b93bab2a650afad5fb4536fc45ae04543391595045035ae19
```
```
$ go run ./cmd/evm verkle chunkify-code 0x11111111111111111111111111111111111111111111111111111111111111111111111111
0x0011111111111111111111111111111111111111111111111111111111111 …
```
=> t8n: add verkle-code-chunk-key and verkle-chunkify-code commands

cmd/evm/internal/t8ntool/execution.go, cmd/evm/main.go
Fixes the t8n filling, and adds the witness output flag to t8n.
=> fix(t8n/exec): Small change to fix t8n verkle filling post rebase.

cmd/evm/internal/t8ntool/execution.go, core/state/database.go
Adds the storage processed flag to t8n. This will be used when we need to set the stride > 0 (as far as my understanding goes).
Tested in execution-spec-tests: the field is now populated as an output from the t8n `result.json` and fed in as an input to next t8n `env.json` during a filling cycle.
=> cmd/evm/t8n: Adds StorageProcessed flag

trie/verkle.go
A bug was identified by replaying Byzantium data which worked correctly with `stride=10k` but failed with `stride=1k`.
After lots of debugging, the issue was related to a wrong identification of an empty account if that same account is in progress of being converted (i.e: storage slots being converted but not yet account basic data).
I've confirmed this fix solves the bad-block in the replay.
=> trie/verkle: fix identification of empty account

core/state/database.go
Over the years, two variables with very similar roles have been created:
* `LastMerkleRoot`, that comes from the time of the replay and is used to retain the base tree. It is set at the end of `IntermediateRoot`
* `baseRoot` which is also the pointer to the root of the base tree, but is coming from the shadowfork codebase.
These two variables do the same thing, and if they are not in sync, weird bugs appear. Hence the need to remove one of them.
This is a cherry-pick of #445 on top of `kaustinen-with-shapella` as something broke the shadowfork system in the t8n branch.
**TODO**
=> merge redundant conversion base tree hash vars

beacon/engine/gen_ed.go, beacon/engine/types.go, consensus/beacon/consensus.go, core/chain_makers.go, core/state_processor_test.go, core/types/block.go, core/types/gen_header_json.go, miner/worker_test.go
This has been suggested during the Nyota interop, and will be tried for the next tesnet. This is so that stateless clients don't have to download two blocks.
This PR currently has two issues:
Tested with lodestar and spindevnets.
=> parent state root in execution witness

.github/workflows/spec-tests.yml, cmd/evm/internal/t8ntool/transition.go, cmd/geth/verkle.go, core/overlay/conversion.go, core/state/access_witness.go, core/state/database.go, core/state/statedb.go, core/state_processor_test.go, core/vm/operations_verkle.go, light/trie.go, trie/secure_trie.go, trie/transition.go, trie/utils/verkle.go, trie/utils/verkle_test.go, trie/verkle.go, trie/verkle_iterator.go, trie/verkle_iterator_test.go, trie/verkle_test.go
=> implement post-nyota verkle costs

.github/workflows/spec-tests.yml
Now that https://github.com/ethereum/execution-spec-tests/pull/761 is merged, we can target `verkle/main` again.
=> ci: target test main branch

.github/workflows/spec-tests-branch.yml, .github/workflows/stable-spec-tests.yml
This PR adds a separate workflow to consume stable fixtures pulled from a defined tag in `execution-spec-tests`.
Depending on the PR, we should make an "expert call" if the fix in the PR should pass or not those stable fixtures, for example:
- If the PR fixes a bug that affects filling, then it might make sense that the job shouldn't pass and that the PR should be merged anyway. This might be a signal to ask for a new `execution-spec-tests` release after the PR is merged.
- If the PR shouldn't affect filling, then this job failing means we might have a regression, and the PR should be further inspected.
=> ci: consume stable fixtures

cmd/evm/internal/t8ntool/execution.go
This PR fixes a bug where adding withdraws to the witness was missing in the filling code (not the execution code).
=> t8n: include withdrawals in witness when filling

core/state/access_witness.go
If `size` is zero, we were touching at least one chunk which is incorrect.
=> witness: fix code touching if size is zero

.github/workflows/stable-spec-tests.yml
This PR contains a temporary fix to solve the problem of the CI not failing when filling and/or consumption fails. This was due to a bug in `consume direct` in the testing library that just got fixed yesterday.
Look at the CI runs:
- The "Consume (stable)" jobs now are failing. This is the correct thing, since we already merged bugfixes for geth. And the current "stable-fixtures" are actually wrong, so the correct thing is that they should fail!
- The filling & consumption jobs don't fail. This is correct, since we're refilling and consuming with this branch itself (not stable one).
=> ci: temporarily switch to fixed consume direct

core/vm/gas_table.go, core/vm/operations_verkle.go
The spec has been updated to charge the witness costs before the 1/64th has been subtracted from the gas allocated to the subcall. This is already fixed on mainnet but it needs to be fixed in this branch for the testnet relaunch.
Fixes #430
=> *CALL: charge witness costs before 1/64th subtraction

core/vm/instructions.go
This PR fixes a bug where in JUMP or positively evaluated JUMPI we weren't charging including the target code-chunk in an invalid jump. 
This is mandatory since it's the only way for a stateless client to know the jump was invalid.
=> vm: charge code-chunk in JUMP and JUMPI if corresponds

core/state/access_witness.go, core/state_processor_test.go, core/vm/evm.go, core/vm/instructions.go
- Remove additional TouchAndChargeContractCreateInit call before 1/64 gas is deducted
- move the TouchAndChargeContractCreateInit call before the collison check and value transfer
=> fix create init witness gas charge

core/vm/operations_verkle.go
This PR makes some changes reg charging at least warm costs for precompile (2929). This was found by @tanishqjasoria by running the fixtures.
=> charge proper warm costs

core/vm/gas_table.go
This PR makes a fix pointed out by @tanishqjasoria
=> witness: don't touch transfer for value-bearing CALLCODE

core/vm/instructions.go
This PR fixes two apparent bugs:
- callGasVariant4762 not ignoring system contracts
- `pushN` touching off-by-one error.
=> spec bugfixes

.github/workflows/spec-tests-branch.yml, .github/workflows/stable-spec-tests.yml
Fix the CI to use `uv` and use `v0.0.4` tag for stable fixtures.
=> ci: new workflows for testing

core/vm/evm.go
`TouchAndChargeContractInit` was being called after increasing the contract's nonce, which corresponds to a write. So charging for the witness costs has to be moved before the nonce is increased.
=> fix: create init order redux

core/state/access_witness.go, core/state_transition.go, core/vm/instructions.go
This PR is solving spec bugs found when @tanishqjasoria is running tentative v0.0.5 fixture set.
=> More spec fixes

.github/workflows/stable-spec-tests.yml
This PR updates our stable-fixtures CI to now target v0.0.5 which now must pass.
=> ci: stable fixtures target v0.0.5

core/vm/gas_table.go
This is a leftover going back to 2021. master geth has greatly changed, and so has the verkle branch, this warning no longer makes sense.
=> remove ineffectual check

.github/workflows/stable-spec-tests.yml, core/state/access_witness.go, core/vm/operations_verkle.go
This PR makes necessary fixes to `witness-charging-order-with-limits` so it passes all v0.0.6 fixtures.
=> Filling fixes

trie/verkle.go
Large balances (>16 bytes) will overwrite the nonce in the basic data leaf. While this can not happen on mainnet, owing to the amount issued, it happens in devmode. This means the nonce will be overwritten with the balance, which is incorrect.
This PR truncates the balance if it's above that threshold.
=> truncate large balances

.github/workflows/stable-spec-tests.yml, cmd/evm/internal/t8ntool/execution.go, core/block_validator.go, core/types/block.go
This PR fixes the new parent state root JSON field name in the witness to match what we get from CL. Additionally, we don't rely on canonical chain numbering to refer to the parent, which doesn't work in syncing mode.
=> types: fix json field name for execution witness parent state root

.github/workflows/stable-spec-tests.yml
This PR updates the version of stable-fixtures to the latest (official) v0.0.7.
=> ci: update stable fixtures version

.github/workflows/stable-spec-tests.yml
This PR updates the stable fixtures to the newest version v0.0.8 which contains new test cases reproducing found bugs in other EL clients in devnet7.
=> ci: update stable tests to v0.0.8

.github/workflows/stable-spec-tests.yml, core/vm/instructions.go
This PR fies a bug found by @lu-pinto while running the latest exec-spec-tests filled by geth.
Note: stabe-fixtures tests is expected to fail since this is a bug fix. "Fill" tests should not fail.
=> blockhash: charge warm costs in witness

core/vm/instructions.go
No check was made to see if the access witness was allocated when charging for an invalid jump.
I have changed it to execute the charge regardless. This is redundant with the interpreter's execution loop, but I think it's easier to read.
=> fix: charge stateless gas on jump

cmd/utils/flags.go, cmd/utils/flags_legacy.go, core/blockchain.go, eth/backend.go, eth/ethconfig/config.go, triedb/pathdb/database.go, triedb/pathdb/journal.go
After the bloating, the size of trie journal will reached into 4GB++, will exceed pebble's write bactch size(4GB), so after the geth stop, it will panic as below:
```
INFO [06-04|00:49:21.888] HTTP server stopped                      endpoint=[::]:8543
INFO [06-04|00:49:21.889] IPC endpoint closed                      url=/data/geth-dev/geth.ipc
INFO [06-04|00:49:21.889] Ethereum protocol stopped
INFO [06-04|00:49:21.889] Transaction pool stopped
INFO [06-04|00:49:23.669] Imported new potential chain segment     number=64 hash=745cbd..6e876d blocks=1 txs=0 mgas=0.000 elapsed=2.055s     mgasps=0.000 triediffs=5.89GiB    triedirty=0.00B
INFO [06-04|00:49:23.670] Persisting dirty state to disk           head=63 root=6ac6c8..71f7de layers=63
WARN [06-04|00:49:23.670] Error performing sealing …
```
=> all: dump trie journal into file

trie/verkle_iterator.go, trie/verkle_iterator_test.go
forgot to push these with the latest PRs.
=> push missing verkle iterator files

core/types/hashes.go, trie/bintrie/binary_node.go, trie/bintrie/empty.go, trie/bintrie/empty_test.go, trie/bintrie/hashed_node.go, trie/bintrie/hashed_node_test.go, trie/bintrie/internal_node.go, trie/bintrie/internal_node_test.go, trie/bintrie/iterator.go, trie/bintrie/key_encoding.go, trie/bintrie/stem_node.go, trie/bintrie/stem_node_test.go, trie/bintrie/trie.go, trie/bintrie/trie_test.go, trie/proof.go, trie/tracer.go, trie/trie.go, trie/trie_reader.go, trie/verkle.go
- Fix node size in SerializeNode
- Track depth in node.Insert
- Copy the key-encoding logic from verkle, making it self-contained
=> Polish binary tree implementations
