gballet/go-ethereum

- cmd/geth/snapshot.go
- core/state/snapshot/conversion.go
- core/state/snapshot/snapshot.go
- go.mod
- go.sum
- Use snapshot iterator instead of trie node iterator
- Make process concurrent
- Save tree nodes to db
> Concurrent snap to verkle via snapshots

- core/state/statedb.go
- core/state_transition.go
- core/types/access_witness.go
- core/vm/evm.go
- core/vm/gas_table.go
- core/vm/instructions.go
- core/vm/interface.go
Co-authored-by: Jared Wasinger <j-wasinger@hotmail.com>
> Charge witness gas when calling/creating a contract

- core/chain_makers.go
- core/state_processor_test.go
- core/types/access_witness.go
- core/types/block.go
- go.mod
- go.sum
- miner/worker.go
- trie/verkle.go
To be used in connection with gballet/go-verkle#181
> Various fixes for rust-verkle proof format compatibility

- trie/utils/verkle.go
This requires to change a check in go-ipa to accept smaller polynomials
> don't evaluate 0-valued coefficients in get_tree_keys

- core/state_processor_test.go
- core/vm/evm.go
When calling an already-created contract, the witness should contain the elements of the code that have been called. Currently, the code contains empty chunks, which shouldn't be the case. It is due to the `IsDeployment` variable always being set to `true`, which should not be the case during a regular contract call.
TODO
> fix: set IsDeployment to false outside of contract creation

- trie/verkle.go
same thing as #106 for `TryUpdate`
> reuse polynomial evaluation in account update

- core/vm/instructions.go
- core/vm/interpreter.go
suggested improvement: lazily evaluate the group index
> core/vm: don't chunk code in interpreter loop

- cmd/geth/verkle.go
- trie/utils/verkle.go
Add the conversion command to the beverly hills branch, in order to reduce the branch count.
> List of changes for converting a sepolia database

- core/state/database.go
- trie/transition.go
- trie/verkle.go
I am out of testing machines while testing #247 so I'm saving this here until I've got a free machine to test it, lest I broke something in this cleanup.
> code cleanup

- core/blockchain.go
A missing `conversion.txt` file would return an error, which broke CI.
> fix: don't error on a missing conversion.txt

- consensus/beacon/consensus.go
- core/state_processor_test.go
- params/config.go
This is so that beverly hills and kaustinen cohabit in a single branch.
> add configuration option to enable proofs to blocks

- consensus/beacon/consensus.go
- consensus/clique/clique.go
- consensus/consensus.go
- consensus/ethash/consensus.go
- miner/worker.go
That extra parameter is no longer needed
> remove StateDB as an extra param to Prepare

- consensus/beacon/consensus.go
- go.mod
- go.sum
> remove pre-state tree warmup

- core/vm/evm.go
> vm: fix access witness recording

- core/vm/instructions.go
Same as #318 but targetting the kaustinen branch
> fix: return error if witness costs OOG in instructions

- trie/utils/verkle.go
This PR bounds the cache used to cache address points up to a total byte limit.
I've tested in the replay branch, and I've confirmed the memory usage has stabilized (both with htop and pprof dumps).
> trie/utils: bound tree key cache

- core/vm/evm.go
This PR changes the order of the witness contract completion charging logic such that a potential out of gas error results in consuming the remaining gas.
> core/vm: fix contract creation witness gas charging logic

- core/vm/instructions.go
This was confusing because updating the contract uses `MAIN_STORAGE_OFFSET` but the reads didn't.
> fix: missing MAIN_STORAGE_OFFSET when reading a block hash from the history contract

- core/overlay/conversion.go
- trie/utils/verkle.go
- trie/verkle.go
This is a series of fixes for issues that were found while testing the nyota costs in replay mode.
> fixes from replaying nyota costs

- core/vm/instructions.go
This PR changes the sentinel error returned for witness additions OOG, so we consume all the remaining gas.
> eip4762: change returned error for witness oog

- go.mod
- go.sum
draft PR to check ethereum/go-verkle#461
> check import fixes from 454

- core/state_processor_test.go
There were some issues in the gas accounting, that appeared when I tried to implement FILL_COST
> fix gas cost detail in verkle state processor test
